<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'is_active', 'hash'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function ($user) {
            $user->userProfile()->delete();
        });
    }

    public function userProfile() {
        return $this->hasOne(UserProfile::class);
    }

    public function deposits() {
        return $this->hasMany(Deposit::class);
    }

    public function withrawals() {
        return $this->hasMany(Withdrawal::class);
    }
}
